/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeriadosRouteImport } from './routes/feriados'
import { Route as PedidosRouteImport } from './routes/pedidos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriadosRoute = FeriadosRouteImport.update({
  id: '/feriados',
  path: '/feriados',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feriados': typeof FeriadosRoute
  '/pedidos': typeof PedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feriados': typeof FeriadosRoute
  '/pedidos': typeof PedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feriados': typeof FeriadosRoute
  '/pedidos': typeof PedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feriados' | '/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feriados' | '/pedidos'
  id: '__root__' | '/' | '/feriados' | '/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeriadosRoute: typeof FeriadosRoute
  PedidosRoute: typeof PedidosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feriados': {
      id: '/feriados'
      path: '/feriados'
      fullPath: '/feriados'
      preLoaderRoute: typeof FeriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeriadosRoute: FeriadosRoute,
  PedidosRoute: PedidosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
