/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeriadosRouteImport } from './routes/feriados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ProducaoRouteImport } from './routes/producao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriadosRoute = FeriadosRouteImport.update({
  id: '/feriados',
  path: '/feriados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feriados': typeof FeriadosRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pedidos': typeof PedidosRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feriados': typeof FeriadosRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pedidos': typeof PedidosRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feriados': typeof FeriadosRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pedidos': typeof PedidosRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/feriados' | '/login' | '/onboarding' | '/pedidos' | '/producao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feriados' | '/login' | '/onboarding' | '/pedidos' | '/producao'
  id:
    | '__root__'
    | '/'
    | '/feriados'
    | '/login'
    | '/onboarding'
    | '/pedidos'
    | '/producao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeriadosRoute: typeof FeriadosRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PedidosRoute: typeof PedidosRoute
  ProducaoRoute: typeof ProducaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feriados': {
      id: '/feriados'
      path: '/feriados'
      fullPath: '/feriados'
      preLoaderRoute: typeof FeriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeriadosRoute: FeriadosRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PedidosRoute: PedidosRoute,
  ProducaoRoute: ProducaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
